language: minimal

services:
  - docker

before_install:
  - docker pull matsengrp/libsbn

script:
  - docker run -v ${PWD}/libsbn:/libsbn -t matsengrp/libsbn /bin/bash -c "ls /libsbn && conda run -n libsbn make -C /libsbn"
