name: libsbn
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - beagle-lib
  - flex
  - jupyter
  - make
  - matplotlib
  - numpy
  - pandas
  - pip
  - pybind11 >=2.3.0
  - pytest
  - scons
  - tensorflow
  - tensorflow-probability
  - pip:
      - enscons
      - tf-nightly-2.0-preview
      - tfp-nightly
