name: libsbn
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - beagle-lib
  - flex
  - make
  - numpy
  - pandas
  - pip
  - pybind11 >=2.3.0
  - pytest
  - scons
  - scipy
  - pip:
      - black
      - click
      - docformatter
      - enscons
      - flake8
      - simplegeneric
      - tensorflow
      - tensorflow-probability
      - tzlocal
  - jupyter
  - r-cowplot
  - rpy2
