{% set name = "beagle-lib" %}
{% set version = "3.1.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/beagle-dev/beagle-lib.git
  git_tag: hmc-clock

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - libtool
  run:
    - libtool

test:
  commands:
    - test -f ${PREFIX}/lib/libhmsbeagle-jni.so # [linux]
    - test -f ${PREFIX}/lib/libhmsbeagle-jni.jnilib # [osx]

about:
  home: https://github.com/beagle-dev/beagle-lib
  license: GPL-3.0+
  license_family: GPL
  summary: general purpose library for evaluating the likelihood of sequence evolution on trees
