name: build_with_make

# Trigger the workflow on push or pull request,
# only on the main branch.
on: 
  push:
    branches: [ main ]

jobs:
  test:
    name: Build with Make, Run Doctests, Run Python test scripts
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: System with Python/Pip

    - name: Build

    