name: build_with_make

# Trigger the workflow on push or pull request,
# only on the main branch.
on: 
  push:
    branches: [ main, 361-migrate-from-travis-ci-org ]
  pull_requests:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
  
  steps:
  - uses: 