name: build_with_make

# Trigger the workflow on push or pull request,
# only on the main branch.
on: 
  push:
    branches: [ ]

jobs:
  test:
    name: Build with Make, Run Doctests, Run Python test scripts
    runs-on: ubuntu-latest
      
  steps:
    - uses: actions/checkout@v2

    - name: System with Python/Pip
    - run: pip --version

    - name: Setup Environment
    - run: |
        pip install -e .
    
    - name: Build 
    - run: make -j20
    
    - name: Run Tests
    - run: make runtest -j20