name: Run test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Prepare build environment
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake zlib1g-dev python3-pip python3-pytest
      - name: Run test
        run: |
          make test
